field: 58b2e318-26cc-47b8-bee2-81369731d72f
fieldLayouts:
  54740fa7-c999-46cf-ac6d-9d485820899c:
    tabs:
      -
        fields:
          133bba22-df33-4432-a49f-198e9c071f22:
            required: false
            sortOrder: 4
          7d7cf5ed-7c41-4d49-ba86-cef811f69683:
            required: false
            sortOrder: 3
          b026d20d-f781-469f-8c4c-5f5c65c66027:
            required: true
            sortOrder: 1
          fa76440e-c84c-4d11-b665-375f32514aaa:
            required: false
            sortOrder: 2
        name: Content
        sortOrder: 1
fields:
  133bba22-df33-4432-a49f-198e9c071f22:
    contentColumnType: string
    fieldGroup: null
    handle: display
    instructions: ''
    name: Display
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Default
            -
              - value
              - default
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Align left'
            -
              - value
              - left
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - 'Align right'
            -
              - value
              - right
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  7d7cf5ed-7c41-4d49-ba86-cef811f69683:
    contentColumnType: string
    fieldGroup: null
    handle: color
    instructions: ''
    name: Color
    searchable: true
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Primary
            -
              - value
              - primary
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Secondary
            -
              - value
              - secondary
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  b026d20d-f781-469f-8c4c-5f5c65c66027:
    contentColumnType: string
    fieldGroup: null
    handle: target
    instructions: ''
    name: Target
    searchable: true
    settings:
      allowSelfRelations: ''
      limit: '1'
      localizeRelations: ''
      selectionLabel: 'Select an entry'
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: ''
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  fa76440e-c84c-4d11-b665-375f32514aaa:
    contentColumnType: text
    fieldGroup: null
    handle: caption
    instructions: 'If blank, the target title will be used.'
    name: Caption
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: language
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 6
