field: 58b2e318-26cc-47b8-bee2-81369731d72f
fieldLayouts:
  373cf894-e8e4-4405-8f2f-9cf8e9c07c32:
    tabs:
      -
        fields:
          25c13312-e79c-4f00-b607-88fab9e35920:
            required: false
            sortOrder: 3
          eb61a6f2-9d63-4730-8ccf-daebb6ba0824:
            required: false
            sortOrder: 2
          ec6b5c42-b633-4465-8f26-2d43d78befe8:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  25c13312-e79c-4f00-b607-88fab9e35920:
    contentColumnType: boolean
    fieldGroup: null
    handle: showDescription
    instructions: ''
    name: 'Show Description'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  eb61a6f2-9d63-4730-8ccf-daebb6ba0824:
    contentColumnType: boolean
    fieldGroup: null
    handle: showTitle
    instructions: ''
    name: 'Show Title'
    searchable: false
    settings:
      default: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  ec6b5c42-b633-4465-8f26-2d43d78befe8:
    contentColumnType: string
    fieldGroup: null
    handle: asset
    instructions: ''
    name: Asset
    searchable: false
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - json
      defaultUploadLocationSource: 'volume:cbbf12d2-97db-4750-8f2d-ea5a5ca1f975'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: '1'
      restrictFiles: '1'
      selectionLabel: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
      singleUploadLocationSubpath: ''
      source: null
      sources:
        - 'volume:cbbf12d2-97db-4750-8f2d-ea5a5ca1f975'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: embed
name: Embed
sortOrder: 7
