fieldLayouts:
  6c0f0e5b-5eda-4477-b091-c5c4eab598de:
    tabs:
      -
        elements:
          -
            instructions: ''
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: postIndex
hasTitleField: true
name: Posts
section: 3792f859-a1b5-44b2-a5d5-4f3df611e91f
sortOrder: 1
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: language
