fieldLayouts:
  e51ac829-2194-411b-b432-c8c37afdded6:
    tabs:
      -
        elements:
          -
            instructions: ''
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: about
hasTitleField: true
name: About
section: 1d3e1ff8-2adc-4e4d-8796-e277ee738837
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: ''
titleTranslationMethod: site
