fieldLayouts:
  fbe1d7ac-ee60-42f7-90eb-973bb5c52cf5:
    tabs:
      -
        elements:
          -
            instructions: ''
            label: Title
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: e4cf9f0d-54a6-4107-beac-daa51b8e5006
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 6c2c7c89-c2ff-4ace-a3e6-aeddab27ab7b
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 9b2aaaa8-c827-4881-955a-86f2df0ea79c
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Content
        sortOrder: 1
handle: post
hasTitleField: true
name: Post
section: 0d69ffe4-360e-4d04-ac30-af0e4381b6ed
sortOrder: 1
titleFormat: ''
titleTranslationKeyFormat: ''
titleTranslationMethod: language
