fieldLayouts:
  ee443750-cc68-4ccf-904c-8348859bbe73:
    tabs:
      -
        elements:
          -
            type: project\modules\drafts\fieldlayoutelements\DraftWarning
          -
            heading: Header
            type: craft\fieldlayoutelements\Heading
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9a302fae-a3bf-4298-8a06-24f8c8f6f335
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 25
          -
            fieldUid: 3ef62a7b-6c6d-470f-88a6-31de5a099b38
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 75
          -
            heading: Content
            type: craft\fieldlayoutelements\Heading
          -
            fieldUid: 58b2e318-26cc-47b8-bee2-81369731d72f
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: topic
hasTitleField: true
name: Topic
section: 338d4897-8545-48cd-bd31-951a6ed52197
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
