tabs:
  -
    elements:
      -
        fieldUid: 0929020c-32b9-4c07-b046-d314e04e7a1d
        instructions: null
        label: null
        required: '0'
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
      -
        fieldUid: 295daf1a-ffb0-4f34-b4e5-d125fbadb823
        instructions: null
        label: null
        required: false
        tip: null
        type: craft\fieldlayoutelements\CustomField
        warning: null
        width: 100
    name: 'Project Settings'
    sortOrder: 1
