fieldLayouts:
  974afb79-459d-481a-ae16-9f12c4b61440:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 3f9c2f2a-8ab0-4aba-bf4e-02d5336d14c0 # Copyright
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: temporaryUploads
hasUrls: true
name: 'Temporary Uploads'
settings:
  path: '@webroot/temporaryuploads'
sortOrder: 4
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\volumes\Local
url: '@baseurl/temporaryuploads'
