fieldLayouts:
  1eadd194-d287-46c7-bd8f-d4d1b40e731b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            autofocus: false
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: temporaryUploads
hasUrls: true
name: 'Temporary Uploads'
settings:
  path: '@webroot/temporaryuploads'
sortOrder: 4
type: craft\volumes\Local
url: '@web/temporaryuploads'
