contentColumnType: string
fieldGroup: fea375f0-9f46-4952-b272-2dcf42b0cce5
handle: footerNavigation
instructions: ''
name: 'Footer Navigation'
searchable: false
settings:
  limit: ''
  localizeRelations: ''
  selectionLabel: ''
  source: null
  sources: '*'
  targetSiteId: null
  validateRelatedElements: ''
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
