contentColumnType: string
fieldGroup: f1d8d989-2bc0-4a0f-b58f-a348276a5596
handle: featuredImage
instructions: 'Check focal point for best use.'
name: 'Featured Image'
searchable: false
settings:
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: ''
  restrictFiles: '1'
  selectionLabel: 'Select an image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
  singleUploadLocationSubpath: '{section.handle|lower}{folderName?''/''~folderName:''''}'
  source: null
  sources:
    - 'volume:8136d7e9-1a74-464d-aef2-3a4f91a5cdda'
    - 'volume:daa73603-4ab8-48c9-800c-139200d9c2e0'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
