contentColumnType: boolean
fieldGroup: 5d1e7a8c-bdb7-48c9-b9a8-9ab55c900868
handle: disableFieldHandles
instructions: 'Disables the display of field handles in edit forms'
name: 'Disable Field Handles'
searchable: false
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
