contentColumnType: string
fieldGroup: fea375f0-9f46-4952-b272-2dcf42b0cce5
handle: primaryNavigation
instructions: ''
name: 'Primary Navigation'
searchable: false
settings:
  contentTable: '{{%matrixcontent_primarynavigation}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
