assets:
  tempVolumeUid: 35c3b3f5-30e7-4780-9ae1-286ee8bd275e
dateModified: 1596118295
email:
  fromEmail: '@EMAIL_ADDRESS'
  fromName: '@EMAIL_SENDER'
  replyToEmail: null
  template: ''
  transportSettings:
    encryptionMethod: tls
    host: '@SMTP_HOST'
    password: '@SMTP_PASSWORD'
    port: '@SMTP_PORT'
    timeout: '10'
    useAuthentication: '1'
    username: '@SMTP_USER'
  transportType: craft\mail\transportadapters\Smtp
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-css:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
    settings:
      additionalCss: "html,body {\r\n  font-size: 15px;\r\n}\r\ninput.text, textarea.text, .text > input, .text > textarea, table.editable textarea, .selectize-text > .selectize-control > .selectize-input {\r\n  font-size: 16px;\r\n}\r\n#global-sidebar {\r\n background-color: #265077;\r\n}\r\n\r\n.sidebar .heading span {\r\n  color: #264a6c;\r\n  font-size: 14px;\r\n  letter-spacing: 1px\r\n}\r\n"
      cssFile: ''
  elementmap:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  embeddedassets:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      cacheDuration: 300
      embedlyKey: ''
      facebookKey: ''
      googleKey: '@GOOGLE_API_KEY'
      iframelyKey: ''
      maxAssetNameLength: 50
      maxFileNameLength: 50
      minImageSize: 16
      parameters:
        -
          __assoc__:
            -
              - param
              - maxwidth
            -
              - value
              - '1160'
        -
          __assoc__:
            -
              - param
              - maxheight
            -
              - value
              - '1080'
      showThumbnailsInCp: true
      soundcloudKey: ''
      whitelist:
        - 'amazon.*'
        - 'amazon.co.*'
        - amcharts.com
        - baidu.com
        - collegehumor.com
        - dailymotion.com
        - deviantart.com
        - embed.ly
        - 'facebook.*'
        - 'facebook.co.*'
        - 'facebook.com.*'
        - fb.com
        - 'google.*'
        - 'google.co.*'
        - 'google.com.*'
        - hulu.com
        - iframely.com
        - imgur.com
        - instagr.am
        - instagram.com
        - kickstarter.com
        - meetup.com
        - meetupstatic.com
        - netflix.com
        - pbs.org
        - nhpbs.org
        - reddit.com
        - soundcloud.com
        - tiktok.com
        - t.co
        - 'twitter.*'
        - 'twitter.co.*'
        - 'twitter.com.*'
        - twimg.com
        - vimeo.com
        - vine.co
        - wikipedia.org
        - wikimedia.org
        - wordpress.com
        - yahoo.com
        - youtu.be
        - youtube.com
        - youtube-nocookie.com
system:
  edition: pro
  live: true
  name: '@SYSTEM_NAME'
  schemaVersion: 3.5.12
  timeZone: Europe/Berlin
