fieldLayouts:
  958d9c22-9855-40ef-b9cf-16af08de416b:
    tabs:
      -
        fields:
          2a586bbf-019e-4c87-bc15-d0b5db0efc98:
            required: false
            sortOrder: 3
          3f9c2f2a-8ab0-4aba-bf4e-02d5336d14c0:
            required: true
            sortOrder: 5
          64c37a78-14f3-4dba-874a-4d4bdd5ba1ee:
            required: true
            sortOrder: 1
          9a302fae-a3bf-4298-8a06-24f8c8f6f335:
            required: false
            sortOrder: 2
        name: 'Site Info'
        sortOrder: 1
handle: siteInfo
name: 'Site Info'
