enableVersioning: true
handle: about
name: About
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  97e0b749-86e3-49f1-918e-9b88758928f4:
    enabledByDefault: true
    hasUrls: true
    template: _layout
    uriFormat: about
  bbbb120d-5d71-4e7c-a164-487e401c4f2c:
    enabledByDefault: true
    hasUrls: true
    template: _layout
    uriFormat: ueber-uns
type: single
